name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Install composer dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm ci

  format:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Run Prettier
        run: prettier --check resources/js

  lint:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run ESLint
        run: eslint --ext .js,.vue --ignore-path .gitignore

  test:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Run Pest
        run: ./vendor/bin/pest

  security:
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Run PHP Security Checker
        run: ./vendor/bin/security-checker security:check

      - name: Run NPM Audit
        run: npm audit
